### ISSUE TITLE
When creating an AsyncTriggerArqSettings

### ISSUE THREAD

**Issue by ghost** [anyei/SFDC-ATARC#1]
Hi, When creating an AsyncTriggerArqSettings it would great if the field **isActive** default to **true**.

Why ?
Because that's why you're creating it in the first place, to be **active**.

**Comment by anyei** [comment]
Thanks for your comment, I'll review and let you know. It makes sense tho.

**Comment by anyei** [comment]
@Fagro Changes included, hope you are happy now  👍

**Comment by ghost** [comment]
I'll test it and thank you !!!

**Comment by anyei** [comment]
Hey @Fagro  i'm closing this issue i believe this is fix, thanks!
