### ISSUE TITLE
Permission Set on "ATARC Process Availability Rule" seems not working

### ISSUE THREAD

**Issue by jeanfrancoisbea** [anyei/SFDC-ATARC#5]
On the Custom Meta Data "**ATARC Process Availability Rule**"  field **Scope__c** we got a value "**Permission Set**" (with a space).
On the class **AsyncTriggerArc**, we got a check with a different value (no space) to compare with "PermissionSet" on scopes.containsKey

        if(scopes.containsKey('**PermissionSet**') && scopes.get('**PermissionSet**').size() > 0){
            for(PermissionSetAssignment psa : [select Assigneeid, PermissionSetId from PermissionSetAssignment where PermissionSetId in :scopes.get('Permission Set') and AssigneeId=:userid]){
                if(!existingScopes.containsKey('PermissionSet')) existingScopes.put('PermissionSet', new set<id>());
                existingScopes.get('PermissionSet').add(psa.PermissionSetId);
            }

And I cannot activate a Handler Class based on the Permission Set ID (maybe because of this) ?!
Is it a real bug or a setting issue on my side ?

**Comment by anyei** [comment]
@jeanfrancoisbea I took a long vacations but now I'm back, sorry I could not get back to you sooner, I'll take a look now if you still use this.

**Comment by anyei** [comment]
Totally true, the value should be PermissionSet not Permission Set in the scope__c field. I'm pushing this change. Thanks @jeanfrancoisbea I hope you put a local fix at least :)
